services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: comp3005a3
      POSTGRES_USER: comp3005
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "8642:5432"
volumes:
  postgres: